# Generated by Django 5.2.13 on 2026-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OCCUPIED", "Occupied"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=15,
            ),
        ),
    ]
