# Generated by Django 5.2.13 on 2026-04-28 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_room_floor_alter_room_room_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated amenities",
                verbose_name="amenities",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="area",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Area in square meters",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="area",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monthly rent price",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="base price",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.IntegerField(
                db_index=True,
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="floor",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="room number"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OCCUPIED", "Occupied"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=15,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200, verbose_name="caption"),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="is primary"),
        ),
    ]
