# Generated by Django 5.2.13 on 2026-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.IntegerField()),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_month", models.IntegerField()),
                ("bill_year", models.IntegerField()),
                ("room_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "electricity_previous",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Previous reading",
                        max_digits=10,
                    ),
                ),
                (
                    "electricity_current",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Current reading",
                        max_digits=10,
                    ),
                ),
                (
                    "electricity_price_per_unit",
                    models.DecimalField(decimal_places=2, default=3500, max_digits=10),
                ),
                (
                    "water_previous",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                (
                    "water_current",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                (
                    "water_price_per_unit",
                    models.DecimalField(decimal_places=2, default=30000, max_digits=10),
                ),
                (
                    "other_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Internet, parking, etc.",
                        max_digits=10,
                    ),
                ),
                ("other_fees_description", models.TextField(blank=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "ordering": ["-bill_year", "-bill_month"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("TRANSFER", "Bank Transfer")],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
            },
        ),
    ]
