# Generated by Django 5.2.13 on 2026-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_month",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="bill_year",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="due_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
