# Generated by Django 5.2.13 on 2026-04-28 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_bill_bill_month_alter_bill_bill_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50, verbose_name="action"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_id",
            field=models.IntegerField(verbose_name="entity ID"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(max_length=50, verbose_name="entity type"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="new_values",
            field=models.JSONField(blank=True, null=True, verbose_name="new values"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="old_values",
            field=models.JSONField(blank=True, null=True, verbose_name="old values"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="bill_month",
            field=models.IntegerField(
                db_index=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="bill month",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="bill_year",
            field=models.IntegerField(
                db_index=True,
                validators=[django.core.validators.MinValueValidator(2000)],
                verbose_name="bill year",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="due_date",
            field=models.DateField(db_index=True, verbose_name="due date"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="electricity_current",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Current reading",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="electricity current",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="electricity_previous",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Previous reading",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="electricity previous",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="electricity_price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=3500,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="electricity price per unit",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="other_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Internet, parking, etc.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="other fees",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="other_fees_description",
            field=models.TextField(blank=True, verbose_name="other fees description"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="paid_date",
            field=models.DateField(blank=True, null=True, verbose_name="paid date"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="room_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="room price",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="total amount"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="water_current",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="water current",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="water_previous",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="water previous",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="water_price_per_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=30000,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="water price per unit",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(verbose_name="payment date"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("TRANSFER", "Bank Transfer")],
                default="CASH",
                max_length=10,
                verbose_name="payment method",
            ),
        ),
    ]
