# Generated by Django 5.2.13 on 2026-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                db_index=True,
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
