# Generated by Django 5.2.13 on 2026-04-28 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_alter_tenant_phone_alter_tenant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="address",
            field=models.TextField(blank=True, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="emergency contact"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="full name"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id_card",
            field=models.CharField(
                help_text="CMND/CCCD",
                max_length=20,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(9)],
                verbose_name="ID card",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=15, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                db_index=True,
                default="ACTIVE",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
