# Generated by Django 5.2.13 on 2026-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("TERMINATED", "Terminated"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=15,
            ),
        ),
    ]
