# Generated by Django 5.2.13 on 2026-04-28 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0003_alter_contract_end_date_alter_contract_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="deposit amount",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(db_index=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="monthly_rent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="monthly rent",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(db_index=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("TERMINATED", "Terminated"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=15,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="terms",
            field=models.TextField(
                blank=True,
                help_text="Contract terms and conditions",
                verbose_name="terms",
            ),
        ),
    ]
